---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.db.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.services.db.name }}
spec:
  ports:
    - name: {{ .Values.services.db.name }}
      port: {{ .Values.services.db.port }}
      targetPort: {{ .Values.services.db.targetPort }}
  selector:
    app: {{ .Values.services.db.name }}
  type: {{ .Values.services.db.type }}

