---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.backend.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: {{ .Values.services.backend.name }}
      port: {{ .Values.services.backend.port }}
      targetPort: {{ .Values.services.backend.targetPort }}
  selector:
    app: {{ .Values.services.backend.name }}
  type: {{ .Values.services.backend.type }}
